### ISSUE TITLE
File picker is slow to show files , slower than fzf-lua native file picker

### ISSUE THREAD

**Issue by hadyelzayady** [otavioschwanck/fzf-lua-enchanted-files#4]
when open the file picker it takes time till showing files noticably slower than fzf-lua files on a repo of 1381 files

**Comment by hadyelzayady** [comment]
Yes I have ripgrep installed and fzflua files uses ripgrep to and it is very fast but with this plugin the picker takes some time to list the files

**Comment by otavioschwanck** [comment]
That neovim version are you using?

Can you record the editor to see if i detect something?

**Comment by searleser97** [comment]
@hadyelzayady  Are you using Windows OS by any chance ? That may be the reason it is slow for you but not for @otavioschwanck

**Comment by hadyelzayady** [comment]
I use macos m1, it is mostly slow due to the two operations of reading and writing the file when opening the picker

**Comment by otavioschwanck** [comment]
@hadyelzayady i pushed a refact for the history fetcher, see if it fixes it

**Comment by hadyelzayady** [comment]
Thanks @otavioschwanck , it really got better than before , but still not as fast as native fzf-lua files or fff.nvim, I like your plugin more than them btw.
 after your update, the performance now is better but there is more that can be done to remove the delay of  showing the files when open the picker
